language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - redis
  - mysql

before_script:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b master
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && phpenv config-add ../unit-tests/ci/phalcon.ini)
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar selfupdate
  - php composer.phar install --dev

before_install:
  - mysql -e "create database IF NOT EXISTS phpress_test;" -uroot

script:
  - mkdir -p tests/fixtures/cache
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c travis/phpunit.xml.dist --coverage-text

after_script:
  - php vendor/bin/coveralls -v
